language: scala
scala:
  - 2.11.12
  - 2.12.8
  - 2.13.0
jdk:
  - openjdk8

install:
  - gem install sass
  - gem install jekyll -v 4.0.0

script:
  - sbt "++ ${TRAVIS_SCALA_VERSION}!" test mimaReportBinaryIssues scalafmtSbtCheck scalafmtCheckAll
  - if [ "$TRAVIS_SCALA_VERSION" = "2.12.8" ]; then sbt docs/makeMicrosite; fi
